[tool.poetry]
name = "support-example"
version = "0.1.0"
description = ""
authors = ["Zach Blumenfeld <zach.blumenfeld@neo4j.com>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
httpx = "^0.25"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
neo4j-chains = {path = "packages/neo4j-chains", develop = true}
tiktoken = "^0.5.2"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
